language: haskell

env:
  - GHCVER=8.0.1 STACK_YAML=stack-travis.yaml

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.stack/

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

# Download and unpack the stack executable
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack setup --no-terminal

# installs GHC if necessary, cleans the previous build,
# build the library, executables, and test suites, and runs the test suites with coverage.
# --no-terminal works around some quirks in Travis's terminal implementation.
script:
  - stack --no-terminal clean
  - stack --no-terminal test --coverage --haddock --no-haddock-deps

# copy haddock to docs
before_deploy:
  - cp -rp `stack path --local-doc-root`/Aeromess* docs

# publish docs to gh-page
deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

after_deploy:
  - rm -rf docs

# report coverage to coveralls.
after_script:
  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-$GHCVER.tar.bz2 | tar -xj
  - ./shc Aeromess Aeromess-test
